export const GET_POPULAR_RECIPES = 'GET_POPULAR_RECIPES';
export const GET_TRENDING_RECIPES = 'GET_TRENDING_RECIPES';
export const GET_NEXT_RECIPES = 'GET_NEXT_RECIPES';

export const NEXT_RECIPES = 'NEXT_RECIPES';
export const PREVIEW_RECIPE = 'PREVIEW_RECIPE';

export const USER_LOGIN = 'USER_LOGIN';
export const USER_REGISTER = 'USER_REGISTER';
export const USER_LOGOUT = 'USER_LOGOUT';
export const USER_FAVORITES = 'USER_FAVORITES';


export const RESET_USER = 'RESET_USER';
